/**
 * Podo UI v2 consumer example (React + Vite).
 *
 * Everything under src/podo/ is generated by the podo CLI (the `podo-ui`
 * workspace dependency provides the bin). To regenerate, run inside
 * examples/react/:
 *
 *   npx podo init --target react --theme landing --yes   # once — writes .podo/ (config.json, lock.json, ...)
 *   npx podo build --force                               # writes src/podo/ (tokens.css, components.css, icons/, ...)
 *
 * src/main.tsx imports the package chrome (podo-ui/styles.css +
 * podo-ui/icons.css) plus the generated src/podo/tokens.css,
 * src/podo/components.css, and src/podo/icons/PodoIcons.css.
 */
import { useState, type ReactNode } from "react";
import {
  Badge,
  Button,
  Checkbox,
  Chip,
  DatePicker,
  Editor,
  Field,
  Icon,
  Input,
  PodoThemeProvider,
  Radio,
  Select,
  Switch,
  Table,
  Textarea,
  Toast,
  Toaster,
  Tooltip,
  Typography,
  toast,
  type DatePickerValue,
} from "@podoui/react";

const FRUITS = [
  { value: "strawberry", label: "딸기" },
  { value: "banana", label: "바나나" },
  { value: "grape", label: "포도" },
  { value: "apple", label: "사과" },
  { value: "orange", label: "오렌지" },
];

/** One titled row of the showcase grid. */
function Section({ title, children }: { title: string; children: ReactNode }) {
  return (
    <section className="example-section">
      <Typography as="span" className="example-section__title">
        {title}
      </Typography>
      <div className="example-section__stage">{children}</div>
    </section>
  );
}

export function App() {
  const [theme, setTheme] = useState<"landing" | "dashboard">("landing");
  const [scheme, setScheme] = useState<"light" | "dark">("light");
  const [date, setDate] = useState<DatePickerValue>({ date: new Date(2026, 6, 21) });
  const [html, setHtml] = useState("<p>Podo UI <strong>에디터</strong> 예제예요.</p>");

  return (
    <PodoThemeProvider theme={theme} colorScheme={scheme}>
      <Toaster position="top-center" />
      <main className="example" data-scheme={scheme}>
        <header className="example-header">
          <div>
            <Typography as="h1">Podo UI React Example</Typography>
            <Typography>
              podo init + podo build 산출물(src/podo)과 podo-ui/styles.css를 그대로 소비하는 Vite
              앱이에요.
            </Typography>
          </div>
          <div className="example-header__controls">
            <Radio
              name="example-theme"
              label="landing"
              checked={theme === "landing"}
              onCheckedChange={() => setTheme("landing")}
            />
            <Radio
              name="example-theme"
              label="dashboard"
              checked={theme === "dashboard"}
              onCheckedChange={() => setTheme("dashboard")}
            />
            <Switch
              label="다크 모드"
              checked={scheme === "dark"}
              onCheckedChange={(on) => setScheme(on ? "dark" : "light")}
            />
          </div>
        </header>

        <Section title="Button">
          <Button onPress={() => toast.success("저장됐어요")}>저장</Button>
          <Button theme="outline-primary" prefix={<Icon name="refresh" />}>
            새로고침
          </Button>
          <Button theme="solid-danger" size="sm">
            삭제
          </Button>
          <Button theme="outline-assistive" size="lg" suffix={<Icon name="chevron-right" />}>
            다음
          </Button>
          <Button disabled>비활성</Button>
        </Section>

        <Section title="Chip / Badge">
          <Chip defaultSelected>선택됨</Chip>
          <Chip theme="outline-weak" prefix={<Icon name="check" size="sm" />}>
            토글
          </Chip>
          <Chip onRemove={() => toast("칩이 제거됐어요")}>제거형</Chip>
          <Badge theme="natural">기본</Badge>
          <Badge theme="danger">99+</Badge>
          <Badge theme="blue">NEW</Badge>
          <Badge theme="green" dot aria-label="온라인" />
        </Section>

        <Section title="Switch / Checkbox / Radio">
          <Switch label="알림" defaultChecked size="md" />
          <Checkbox label="약관 동의" defaultChecked />
          <Checkbox label="부분 선택" indeterminate />
          <Radio name="fruit" label="포도" defaultChecked />
          <Radio name="fruit" label="딸기" />
        </Section>

        <Section title="Input / Textarea / Field">
          <Input placeholder="검색어" prefix={<Icon name="search" />} />
          <Input defaultValue="12000" suffixText="원" />
          <Input placeholder="오류 상태" invalid />
          <Field
            label="자기소개"
            subLabel="선택"
            helperText="500자까지 입력할 수 있어요."
            countMax={500}
          >
            <Textarea placeholder="내용을 입력해 주세요" />
          </Field>
        </Section>

        <Section title="Select">
          <Select placeholder="과일 선택 (단일)" options={FRUITS} defaultValue="grape" />
          <Select
            placeholder="과일 선택 (다중)"
            options={FRUITS}
            multiple
            clearable
            defaultValues={["grape", "strawberry"]}
          />
        </Section>

        <Section title="Tooltip / Toast">
          <Tooltip label="위쪽 툴팁이에요" position="top">
            <Button theme="outline-primary" size="sm">
              호버해 보세요
            </Button>
          </Tooltip>
          <Button size="sm" onPress={() => toast.danger("저장에 실패했어요", { manual: true })}>
            수동 닫기 토스트
          </Button>
          <Toast state="info" caption="Toaster 없이 배치한 정적 카드예요.">
            정적 토스트 카드
          </Toast>
        </Section>

        <Section title="Table">
          <Table type="grid" checkbox defaultSelected={[0]}>
            <thead>
              <tr>
                <th>과일</th>
                <th>재고</th>
                <th>상태</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>포도</td>
                <td>120</td>
                <td>
                  <Badge theme="success">판매 중</Badge>
                </td>
              </tr>
              <tr>
                <td>딸기</td>
                <td>0</td>
                <td>
                  <Badge theme="danger">품절</Badge>
                </td>
              </tr>
              <tr data-disabled="true">
                <td>바나나</td>
                <td>-</td>
                <td>
                  <Badge theme="gray">준비 중</Badge>
                </td>
              </tr>
            </tbody>
          </Table>
        </Section>

        <Section title="Icon / Typography">
          <Icon name="calendar" size="sm" />
          <Icon name="menu" />
          <Icon name="time" size="lg" />
          <Icon name="search" size="lg" decorative={false} aria-label="검색" />
          <Typography as="h1" variant="h1">
            제목 타이포그래피
          </Typography>
          <Typography>본문 타이포그래피예요.</Typography>
        </Section>

        <Section title="DatePicker">
          <Field label="예약일 (controlled)">
            <DatePicker value={date} onChange={setDate} format="y-m-d" />
          </Field>
          <Field label="기간 (uncontrolled)">
            <DatePicker
              mode="period"
              defaultValue={{ date: new Date(2026, 6, 1), endDate: new Date(2026, 6, 15) }}
            />
          </Field>
        </Section>

        <Section title="Editor">
          <Editor
            value={html}
            onChange={setHtml}
            height="220px"
            toolbar={["undo-redo", "paragraph", "text-style", "align", "list", "link", "code"]}
          />
        </Section>
      </main>
    </PodoThemeProvider>
  );
}
