import { normalizeAliasReference, type ComponentDocument } from "@podoui/spec";

export type CodegenTarget = "web" | "react" | "hono" | "native";

export interface GeneratedFile {
  path: string;
  contents: string;
}

export interface GenerateComponentFilesOptions {
  specs: ComponentDocument[];
  targets: CodegenTarget[];
  outDir?: string;
}

export interface ComponentTemplateContext {
  spec: ComponentDocument;
  exportName: string;
  tagName: string;
}

export type ComponentTemplate = (context: ComponentTemplateContext) => string;

export const generatedFileHeader =
  "/* This file is generated by @podoui/codegen. Do not edit directly. */";

export const componentTemplates: Record<CodegenTarget, ComponentTemplate> = {
  web: ({ exportName, tagName }) =>
    [
      `export const ${exportName}ElementName = ${JSON.stringify(tagName)};`,
      `export function define${exportName}(): string {`,
      `  return ${exportName}ElementName;`,
      "}",
    ].join("\n"),
  react: ({ exportName }) =>
    [
      `export { ${exportName} } from "@podoui/react";`,
      `export type { ${exportName}Props } from "@podoui/react";`,
    ].join("\n"),
  hono: ({ exportName }) => `export { ${exportName} } from "@podoui/hono";`,
  native: ({ exportName }) =>
    [
      `export { ${exportName} } from "@podoui/native";`,
      `export type { Native${exportName}Props } from "@podoui/native";`,
    ].join("\n"),
};

export function generateComponentFiles(options: GenerateComponentFilesOptions): GeneratedFile[] {
  const outDir = trimSlashes(options.outDir ?? "generated");
  const specs = [...options.specs].sort((a, b) => a.id.localeCompare(b.id));
  const targets = [...options.targets].sort((a, b) => a.localeCompare(b));
  const files: GeneratedFile[] = [];

  for (const target of targets) {
    for (const spec of specs) {
      if (!spec.targets[target]?.supported) {
        continue;
      }

      const exportName = toPascalCase(spec.id);
      const context: ComponentTemplateContext = {
        spec,
        exportName,
        tagName: `podo-${spec.id}`,
      };

      files.push({
        path: `${outDir}/${target}/${spec.id}.${target}.ts`,
        contents: `${generatedFileHeader}\n${componentTemplates[target](context)}\n`,
      });
    }
  }

  return files.sort((a, b) => a.path.localeCompare(b.path));
}

export function generateIndexFile(files: GeneratedFile[], outDir = "generated"): GeneratedFile {
  const base = trimSlashes(outDir);
  const exports = files
    .map((file) => file.path.replace(`${base}/`, "./").replace(/\.ts$/, ".js"))
    .sort()
    .map((path) => `export * from ${JSON.stringify(path)};`)
    .join("\n");

  return {
    path: `${base}/index.ts`,
    contents: `${generatedFileHeader}\n${exports}\n`,
  };
}

export function assertIdempotent(filesA: GeneratedFile[], filesB: GeneratedFile[]): void {
  const stableA = JSON.stringify(filesA, null, 2);
  const stableB = JSON.stringify(filesB, null, 2);
  if (stableA !== stableB) {
    throw new Error("Codegen output is not idempotent for the same inputs.");
  }
}

function componentBindingVar(id: string, key: string): string {
  return `--podo-${id}-${key.replace(/\./g, "-")}`;
}

function aliasToCssVar(reference: string): string {
  // A binding may be a raw CSS value (e.g. "42px") instead of a token alias; emit
  // raw values verbatim and only token aliases as `var(--podo-…)`.
  if (!/^\{.+\}$/.test(reference) && !reference.startsWith("#/")) {
    return reference;
  }
  return `var(--podo-${normalizeAliasReference(reference).replace(/\./g, "-")})`;
}

// Escape a variant value for safe use inside a quoted CSS attribute selector
// ([data-x="<value>"]). Variant values are free-form spec strings.
function escapeCssAttributeValue(value: string): string {
  return value.replace(/[\\"\n\r\f]/g, (char) => {
    if (char === "\n") return "\\A ";
    if (char === "\r") return "\\D ";
    if (char === "\f") return "\\C ";
    return `\\${char}`;
  });
}

function cssRule(selector: string, declarations: Array<[string, string]>): string | undefined {
  if (!declarations.length) {
    return undefined;
  }
  const body = declarations.map(([property, value]) => `  ${property}: ${value};`).join("\n");
  return `${selector} {\n${body}\n}`;
}

/**
 * Emit a spec-driven component token CSS layer. Each component's token bindings
 * become CSS custom properties named after the binding (`--podo-<id>-<part>-<prop>`)
 * bound to the referenced token var, with per-variant-value and per-state
 * overrides scoped by `[data-<variant>="<value>"]` / `[data-state="<state>"]`.
 * Editing a component's variant/state token bindings therefore changes build
 * output. Deterministic (sorted by id, then binding key).
 */
export function emitComponentTokenCss(specs: ComponentDocument[]): string {
  const blocks: string[] = [];
  const sorted = [...specs].sort((a, b) => a.id.localeCompare(b.id));
  const sortedDecls = (map: Record<string, string>, id: string): Array<[string, string]> =>
    Object.entries(map)
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([key, reference]) => [componentBindingVar(id, key), aliasToCssVar(reference)]);

  for (const spec of sorted) {
    const base = `.podo-${spec.id}`;
    // Hidden layers (Figma eye toggle persisted on anatomy parts) reach build
    // output as real display rules: the root hides the whole component; other
    // parts hide their `[data-part]` element.
    for (const part of [...spec.anatomy].sort((a, b) => a.name.localeCompare(b.name))) {
      if (!part.hidden) continue;
      const selector =
        part.name === "root" ? base : `${base} [data-part="${escapeCssAttributeValue(part.name)}"]`;
      blocks.push(cssRule(selector, [["display", "none"]]) as string);
    }
    // Base = component-level tokens folded with variant-level tokens (which apply
    // across the whole variant axis), so edits to either reflect in output.
    const baseMap: Record<string, string> = { ...spec.tokens };
    for (const variant of spec.variants) {
      Object.assign(baseMap, variant.tokens ?? {});
    }
    const baseRule = cssRule(base, sortedDecls(baseMap, spec.id));
    if (baseRule) {
      blocks.push(baseRule);
    }
    for (const variant of spec.variants) {
      for (const value of Object.keys(variant.valueTokens ?? {}).sort()) {
        const map = variant.valueTokens?.[value] ?? {};
        const selector = `${base}[data-${variant.name}="${escapeCssAttributeValue(value)}"]`;
        const rule = cssRule(selector, sortedDecls(map, spec.id));
        if (rule) {
          blocks.push(rule);
        }
      }
    }
    // Compound variant conditions: every named axis constrains the selector.
    for (const combination of spec.combinations ?? []) {
      const selector = Object.entries(combination.when)
        .sort(([a], [b]) => a.localeCompare(b))
        .reduce(
          (acc, [axis, value]) => `${acc}[data-${axis}="${escapeCssAttributeValue(value)}"]`,
          base
        );
      const rule = cssRule(selector, sortedDecls(combination.tokens, spec.id));
      if (rule) {
        blocks.push(rule);
      }
    }
    for (const state of [...spec.states].sort((a, b) => a.name.localeCompare(b.name))) {
      const rule = cssRule(
        `${base}[data-state="${state.name}"]`,
        sortedDecls(state.tokens ?? {}, spec.id)
      );
      if (rule) {
        blocks.push(rule);
      }
    }
  }

  return blocks.length
    ? `${generatedFileHeader}\n${blocks.join("\n\n")}\n`
    : `${generatedFileHeader}\n`;
}

function toPascalCase(value: string): string {
  return value
    .split(/[-_]/g)
    .filter(Boolean)
    .map((part) => `${part[0]?.toUpperCase() ?? ""}${part.slice(1)}`)
    .join("");
}

function trimSlashes(value: string): string {
  return value.replace(/^\/+|\/+$/g, "");
}
